linters:
  enable:
    # Default linters, plus these:
    - goconst
    - gocritic
    - gocognit
    - gofmt
    - gosec
    - misspell
    - scopelint
    - bodyclose

run:
  skip-files:
    # Skip all dynamically generated files
    - bindata.go
    - generated.go

issues:
  exclude:
    # Disable scopelint errors on table driven tests
    - Using the variable on range scope `tc` in function literal
